#!/bin/sh

export LANG=C

usage()
{
  echo
  echo "Create RFRemix Live images based on Fedora 15 package base"
  echo "from internet."
  echo
  echo "create-live <imagename> <i686|x86_64|all> <version>"
  echo "	-g - GNOME LiveCD"
  echo "	-k - KDE LiveCD"
  echo "	-x - XFCE LiveCD"
  echo "	-l - LXDE LiveCD"
  echo "	-m - MATE LiveCD"
  echo "	-d - GNOME, KDE, XFCE, LXDE LiveDVD"
  echo "	-K - KDE LiveCD KDE Minimal"
  exit 2
}

ok()
{
  echo -e "\t\t\\033[0;32m[  OK  ]\\033[0;39m"
}

fail()
{
  echo -e "\t\t\\033[0;31m[ FAIL ]\\033[0;39m"
}

faile()
{
  echo -e "\t\t\\033[0;31m[ FAIL ]\\033[0;39m"
  exit 1
}

if [ `id -u` -ne 0 ]; then
  echo "Login as root! Abort..."
  exit 3
fi

BUILDDIR="$(pwd)"
CONFIGPATH="$BUILDDIR/kickstarts"
LOGFILE="$BUILDDIR/build-$(date +%Y%m%d%H%M).log"

if [ ! -d "/usr/share/spin-kickstarts/" -a ! -d "$BUILDDIR/kickstarts" ]; then
  echo "No config found. Abort..."
  exit 5
fi

case "$1" in
  -g)
    DIST="Live-GNOME"
    CONFIG="$CONFIGPATH/rfremix-livecd-desktop-ru_RU.ks"
    ;;
  -k)
    DIST=("Live-KDE")
    CONFIG=("$CONFIGPATH/rfremix-livecd-kde-ru_RU.ks")
    ;;
  -x)
    DIST=("Live-XFCE")
    CONFIG=("$CONFIGPATH/rfremix-livecd-xfce-ru_RU.ks")
    ;;
  -l)
    DIST=("Live-LXDE")
    CONFIG=("$CONFIGPATH/rfremix-livecd-lxde-ru_RU.ks")
    ;;
  -m)
    DIST=("Live-MATE")
    CONFIG=("$CONFIGPATH/rfremix-livecd-mate-ru_RU.ks")
    ;;
  -d)
    DIST=("LiveDVD")
    CONFIG=("$CONFIGPATH/rfremix-livedvd-desktop-ru_RU.ks")
    ;;
  -K)
    DIST=("Live-KDE-minimal")
    CONFIG=("$CONFIGPATH/rfremix-livecd-kde-minimal-ru_RU.ks")
    ;;
  -a)
    DIST=("Live-GNOME" "Live-KDE" "Live-XFCE" "Live-LXDE" "Live-MATE" "Live-KDE-minimal")
    CONFIG=("$CONFIGPATH/rfremix-livecd-desktop-ru_RU.ks"
            "$CONFIGPATH/rfremix-livecd-kde-ru_RU.ks"
            "$CONFIGPATH/rfremix-livecd-xfce-ru_RU.ks"
            "$CONFIGPATH/rfremix-livecd-lxde-ru_RU.ks"
            "$CONFIGPATH/rfremix-livecd-mate-ru_RU.ks"
            "$CONFIGPATH/rfremix-livecd-kde-minimal-ru_RU.ks")
    ;;
  -clean-all)
    rm -f *.iso *-CHECKSUM
    exit 0
    ;;
  *)
    usage
    ;;
esac

case "$2" in
  all)
    ARCH="i686 x86_64"
    ;;
  i686)
    ARCH="i686"
    ;;
  x86_64)
    ARCH="x86_64"
    ;;
  *)
    usage
    ;;
esac

# can we build x86_64 on an i386?
echo $ARCH | grep x86_64 > /dev/null 2>&1

if [ "$?" -eq 0 -a "$(uname -m)" != "x86_64" ]; then
  echo "You cannot build x86_64 images on an i386 arch. Abort..."
  exit 10
fi

version=$3
release_version=$(echo $version | awk -F[.-] '{ print $1 }')

if [ "x$version" == "x" ]; then
  usage
fi

echo -n "Creating Build directory                       "
mkdir -p $BUILDDIR/tmp && mkdir -p $BUILDDIR/kickstarts && ok || faile

if [ "$(ls -A $BUILDDIR/kickstarts)" ]; then
  echo "$BUILDDIR/kickstarts/ is not empty"
else
  echo -n "Copying kickstarts files                       "
  cp /usr/share/spin-kickstarts/rfremix-live*ks \
    $BUILDDIR/kickstarts/ && ok || faile
fi

LOCAL=$4

if [ "x$LOCAL" == "x--local" ]; then
  sed -i 's!http://mirrors.rfremix.ru!http://localhost!g' \
    $BUILDDIR/kickstarts/rfremix-live-base.ks
  sed -i 's!http://mirrors.rfremix.ru!http://localhost!g' \
    $BUILDDIR/kickstarts/rfremix-live-mini.ks
fi

echo "Logging to $LOGFILE"

pushd $BUILDDIR > /dev/null

setenforce 0

for arch in $ARCH; do
  for i in `seq 0 $((${#DIST[*]}-1))`; do
    if [ ! -f "${CONFIG[i]}" ]; then
      echo "${CONFIG[i]}" does not exist.
      exit 10
    fi

    rm -f RFRemix-$version-$arch-${DIST[i]}.iso
    rm -f RFRemix-$version-$arch-${DIST[i]}-CHECKSUM

    LABEL=$(echo RFRemix-$version-$arch-${DIST[i]}.iso | sed 's!\.iso!!g' | cut -b 1-32)

    echo -n "Creating RFRemix-$version-$arch-${DIST[i]}.iso "

    setarch $arch livecd-creator --releasever=release_version -v -d -t $BUILDDIR/tmp --cache=$BUILDDIR/tmp \
        -f $LABEL --product=RFRemix --title="RFRemix $version" -c ${CONFIG[i]} >> $LOGFILE 2>&1 && \
      if [ "$LABEL.iso" != "RFRemix-$version-$arch-${DIST[i]}.iso" ]; then
        mv $LABEL.iso RFRemix-$version-$arch-${DIST[i]}.iso; fi && \
      sha256sum RFRemix-$version-$arch-${DIST[i]}.iso > \
        RFRemix-$version-$arch-${DIST[i]}-CHECKSUM && ok || fail
  done
done

popd > /dev/null

setenforce 1
